### ISSUE TITLE
produce module build for bundling and tree shaking support

### ISSUE THREAD

**Issue by autumnblazey** [colinhacks/zod#294] opened 2021-01-16 07:23 UTC
It would be nice if you could also produce and publish an ES module build of zod for bundler consumption. I can probably send a PR when I get the chance to.

[here is an article](https://rollupjs.org/guide/en/#what-is-tree-shaking) if you're not familiar with bundling and tree shaking. [Another article](https://rollupjs.org/guide/en/#publishing-es-modules) on how to point bundlers at the module build

Thanks for considering! (ps i dont use rollup lol)

**Comment by jacksteamdev** [comment] 2021-02-26 20:53
@autumnblazey An ESM build would be great! Take a look at #175 and #215 for some background.

**Comment by colinhacks** [comment] 2021-03-18 07:31
The newest version of Zod 3 (`zod@3.0.0-alpha.7`) includes an ESM bundle. @autumnblazey if you have a way to test that it's working with your bundler, that would be super useful. Just do `npm install zod@next` to get the latest version.

**Comment by autumnblazey** [comment] 2021-03-19 17:58
will do when i can!

**Comment by autumnblazey** [comment] 2021-03-30 05:24
so far, it seems to work as expected, I'm not seeing any errors in the browser console

**Comment by colinhacks** [comment] 2021-04-25 21:56
Fantastic. Closing this.

**Closed by colinhacks** 2021-04-25 21:56 UTC

**Comment by ekwoka** [comment] 2023-02-21 14:02
It doesn't seem like tree shaking works at all.

If you use just `string()` the result is the same as if you use every possible export.

**Comment by simlevesque** [comment] 2023-03-27 17:42
> It doesn't seem like tree shaking works at all.
> 
> If you use just `string()` the result is the same as if you use every possible export.

I can confirm this.

**Comment by AlanLes** [comment] 2024-03-12 06:38
It looks like this has been fixed in [this PR](https://github.com/colinhacks/zod/pull/2850), but is still not merged and has been waiting for several months.
