### ISSUE TITLE
`infer` incorrectly marks property as `required` for `any().optional()` after upgrading to v3.3.4

### ISSUE THREAD

**Issue by divpreet** [colinhacks/zod#519] opened 2021-07-06 05:59 UTC
After upgrading from v3.2.0 to v3.3.4, for an object like ->
```
const TestSchema = z.object({
  options: z
    .object({
      message: z.string().optional(),
      convertOption: z.string().optional(),
      displayOrder: z.any().optional(),
    })
    .optional(),
})
```
and
`z.infer<typeof TestSchema>` 
results in 
`{options?: {message?: string | undefined, convertOption?: string | undefined, displayOrder: any} | undefined}` 
instead of marking `displayOrder?: any`

Using `number` or `string` instead of `any` marks it as optional correctly.

**Comment by colinhacks** [comment] 2021-07-06 16:08
Fixed in 3.4.0.

@lilred fixing this requires rolling back #494. Due to the nature of how TypeScript merges types, all `any/unknown` schemas will either be interpreted as required or optional. 

```ts
type asdf = unknown | undefined; // unknown
type qwer = any | optional; // any
```
There's no way to discriminate between an "optional" unknown and a "required" unknown becauase TypeScript merges the `| undefined` into the `unknown`. I didn't realize this at the time. The only way to fix this would be to rewrite the `requiredKeys` alias to operate in the runtime/Zod domain instead of in the "inferred type" domain, which would be a big messy recursive alias that's error prone and wouldn't work with third-party combinators.

Since `undefined` is assignable to both unknown and any, I think making all unknown/any schemas optional in objects is the best approach.

**Comment by lilred** [comment] 2021-07-06 20:18
That's unfortunate. I'll give this a look when I have time in case I can find another way. (Not super hopeful but these are always interesting puzzles.)

Did anyone add unit tests addressing @divpreet's issue to prevent regressions?

**Comment by colinhacks** [comment] 2021-07-06 21:53
Test added in 5a14940.

**Comment by divpreet** [comment] 2021-07-06 23:28
Works fine with the fix. Tested on v3.5.1
Can close this if you like.

**Closed** 2021-07-07 02:52 UTC
