### ISSUE TITLE
ZodUnion gets parsed, despite being invalid

### ISSUE THREAD

**Issue by SlateDave** [colinhacks/zod#671] opened 2021-09-28 10:51 UTC
Hi!

Based on this simple example:

```typescript
const NumberOrNonEmptyString = z.union( [
    z.number(),
    z.string().nonempty()
] );

NumberOrNonEmptyString.parse( '' ); // Passes
```

It passes the ``.nonempty()`` check despite being passed an empty string.

**Comment by colinhacks** [comment] 2021-09-28 23:11
Should be fixed if you upgrade to `zod@latest`, let me know if it isn't.

Duplicate of https://github.com/colinhacks/zod/issues/668. Be sure to include the installed version when you create issues like this.

**Comment by SlateDave** [comment] 2021-09-29 15:22
Sorry, I have disregarded that. Now it works, however, in the same example I encountered another problem with ZodUnion. I am on version 3.9.4 and it ignores my custom invalid type message.

```typescript
const NumberOrNonEmptyString = z.union( [
    z.number(),
    z.string().nonempty()
], {
    invalid_type_error: 'A custom message'
} );

NumberOrNonEmptyString.parse( true );
```

In this example the thrown ZodError results in the property ``"message": "Invalid input"`` instead of `` "message": "A custom message"``

**Comment by SlateDave** [comment] 2021-10-05 16:04
@FlorianWendelborn Yeah, you're absolutely right. Let be just check first if the issue still persists and then I will create a new issue if applicable.

**Closed** 2021-10-05 16:05 UTC
