### ISSUE TITLE
Feature Request: Custom error message for primitive type errors

### ISSUE THREAD

**Issue by pfcodes** [colinhacks/zod#281] opened 2020-12-31 03:38 UTC
Yup allows for defining an error message for failed type checks via a `typeError(message: string)` operator. Doesn't seem like there's anything like this in Zod. I'd rather have custom humanized error messages than an unchangeable: `Expected number, received nan`.

**Comment by BigWhale** [comment] 2021-01-18 13:15
I have just switched from Yup to Zod, because type inferring is better and it works better with react-hook-forms. I have a problem with this, too. I'm working with Zod 2 and there seems to be no way of handling errors like this.

I have a schema like this:

`
const ZodTestSchema = z.object({
  name: z.string().max(80, 'Name too long.').nonempty('Name required.'),
  age: z.transformer(z.string(), z.number(), (value) => parseInt(value, 10)).optional()
  .refine((v) => v > 0, { message: 'Age must be positive.' }),
  options: z.object({
    label: z.string(),
      value: z.string().nonempty('Option value required.'),
  }),
`
And there's no way (or I couldn't find any) to customize messages for type errors or messages if z.object() is missing.

**Comment by dougg0k** [comment] 2021-03-28 13:43
Yes, would be cool to have an option to modify the default "Required" message whether an `z.object()` is missing or not.

**Comment by colinhacks** [comment] 2021-03-30 01:48
@dougg0k @pfcodes @BigWhale You can do all of this with error maps in Zod 3. 

https://github.com/colinhacks/zod/blob/v3/ERROR_HANDLING.md#customizing-errors-with-zoderrormap

**Comment by kompot** [comment] 2021-03-30 08:39
@colinhacks 

As far as I see that's somewhat fixes the problem. As `ZodErrorMap` can only be customised in global context.

I'm also migrating from `yup` and within form validation I have this pattern.

As soon as validation triggered — show the most detailed error relevant for the field (and not common one).

```typescript
const email = 
  yup
    .string()
    .email('Email address format is not valid')
    .required('Please fill in your email address');
```

As you can see — there's special value for `required`. I could have gone down the road you suggest and render just common localised message `Please fill in this field` but in my opinion it's better to render `Please fill in your email address` as a hint (and in case there's already some invalid input — then `Email address format is not valid`). Of course YMMV depending on context and if you do some generic validation then maybe common type error would be enough. But in my opinion it's not. I've ended up just rendering no text error at all and highlight the field in red in case nothing was entered.

Thanks for your awesome job on this project!

**Comment by mildfuzz** [comment] 2021-04-01 15:30
For me, applying this to the parse method won't work because I am actually using the zodResolver with React Hooks Form, so do not call parse in my own code

**Comment by mildfuzz** [comment] 2021-04-01 15:39
This is my current work around

```typescript
function zodCustomRequired<T>(schema: ZodType<T>, message: string) {
  return schema.nullable().refine((data) => !!data, message)
}
```

but I think my prefered pattern would be to *either* assume all types are optional unless marked as required (and allow custom message in that method) *or* to add a optional message to the constructor

**Comment by colinhacks** [comment] 2021-04-25 02:34
Duplicate of #97, this is on the roadmap. Also - PR welcome.

**Closed by colinhacks** 2021-04-25 02:34 UTC
