### ISSUE TITLE
Validations being skipped when using preprocessor

### ISSUE THREAD

**Issue by dylantf** [colinhacks/zod#3237] opened 2024-02-14 07:58 UTC
I just came across an issue during an upgrade from 3.21.4 to 3.22.x that caused some of our tests to break. When validating an object, we expect to see an error object containing all of the failed validations. However, when using preprocessing functions, not all of the fields containing errors are appearing in the error object.

Example schema:
```ts
const schema = z.object({
  foo: z.string().min(4),
  bar: z.preprocess((val) => val, z.string().min(4)),
});

const values = {
  foo: "abc",
  bar: "abc",
};
```

Before 3.22.0, this would show errors in both `foo` and `bar`, but now only shows an error for `foo`. If you remove the preprocess, it works correctly and you get errors for both. If both fields have preprocessors, it seems a bit random -- maybe the order they are defined in determines where the validation stops, as we still only get `foo`.

**Comment by JacobWeisenburger** [comment] 2024-02-14 14:06
Is this what you are looking for?

```ts
const schema = z.object( {
    foo: z.string().min( 4 ),
    bar: z.any().transform( val => val ).pipe( z.string().min( 4 ) )
} )

const result = schema.safeParse( { foo: 'abc', bar: 'abc' } )
!result.success && console.log( result.error.issues )
// [
//     {
//         code: "too_small",
//         minimum: 4,
//         type: "string",
//         inclusive: true,
//         exact: false,
//         message: "String must contain at least 4 character(s)",
//         path: [ "foo" ],
//     }, {
//         code: "too_small",
//         minimum: 4,
//         type: "string",
//         inclusive: true,
//         exact: false,
//         message: "String must contain at least 4 character(s)",
//         path: [ "bar" ],
//     }
// ]
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by JacobWeisenburger** [comment] 2024-02-14 14:07
Duplicate of https://github.com/colinhacks/zod/issues/3123

**Comment by dylantf** [comment] 2024-02-14 14:10
Unless there was an intentional API change to abort validating early, I think this is a bug as the field is not present in the errors object at all if any other fields failed validation.

**Comment by JacobWeisenburger** [comment] 2024-02-14 14:12
Closing in favor of https://github.com/colinhacks/zod/issues/3123

**Closed by JacobWeisenburger** 2024-02-14 14:12 UTC
Labels: bug-confirmed, duplicate
