### ISSUE TITLE
Add input to the errors

### ISSUE THREAD

**Issue by mmahalwy** [colinhacks/zod#815] opened 2021-12-07 18:55 UTC
Given this example:

```ts
 {
    "code": "not_multiple_of",
    "multipleOf": 0.001,
    "message": "Should be multiple of 0.001",
    "path": [
      33,
      "shepherdMgaFee"
    ]
  },
  {
    "code": "not_multiple_of",
    "multipleOf": 0.001,
    "message": "Should be multiple of 0.001",
    "path": [
      33,
      "brokerCommission"
    ]
  },
```

It's very difficult to identify what the input was that caused this to error. Ideally, the errors would include the input that caused this to fail. For example:

```ts
 {
    "code": "not_multiple_of",
    "multipleOf": 0.001,
    "message": "Should be multiple of 0.001",
    "path": [
      33,
      "shepherdMgaFee"
    ],
    "input": 1
  },
```

**Comment by MrAwesome** [comment] 2022-01-12 18:40
I believe this is a duplicate of #595.

The TL;DR is that this is a feature multiple people want, but it isn't a universally-desired feature for everyone in all cases, since it could lead to the logging of sensitive data for some users.

**Comment by JacobWeisenburger** [comment] 2022-02-27 14:15
This issue seems to be addressed. May I close this?

**Comment by MrAwesome** [comment] 2022-02-27 19:05
The PR to implement this is still awaiting approval/merge, so not quite yet

**Comment by JacobWeisenburger** [comment] 2022-02-27 21:25
Sounds good

**Closed** 2022-02-28 04:36 UTC
Labels: enhancement
