### ISSUE TITLE
.catch() does not preserve type with .optional()

### ISSUE THREAD

**Issue by firemuzzy** [colinhacks/zod#1737] opened 2022-12-22 05:14 UTC
zod version: `3.20.2`
issue: `z.string().optional().catch(undefined)` comes out as `string` instead of `string | undefined`

```
const someSchema = z.object( {
  optionalCatch: z.string().optional().catch(undefined)
})
type Some = z.infer<typeof someSchema>

type WrongType = Some["optionalCatch"]
```

the type of `WrongType` comes out as `string` instead of `string | undefined` however the argument to `catch` does test for undefined.

**Comment by santosmarco-caribou** [comment] 2022-12-22 06:30
I believe `ZodCatch` was designed wrongfully. I've already opened a PR to fix it.

https://github.com/colinhacks/zod/pull/1733

cc: @colinhacks

**Comment by JacobWeisenburger** [comment] 2022-12-24 19:21
It looks like this PR was merged. Can we close this issue?

**Comment by santosmarco-caribou** [comment] 2022-12-25 12:28
Yes

**Closed** 2022-12-25 13:18 UTC
