### ISSUE TITLE
Sending validator as first-class-function verifies badly

### ISSUE THREAD

**Issue by merisbahti** [colinhacks/zod#248] opened 2020-12-03 20:24 UTC
See this code:

```typescript
import * as z from "zod";

const callback = (predicate: (val: string) => boolean) => {
  return predicate("hello");
};

console.log(callback(z.string().is)); // false!?
console.log(callback((value) => z.string().is(value))); // true
```
https://codesandbox.io/s/priceless-shadow-diu6n?file=/src/index.ts

Passing the `is` function seems to return a bad value, however, creating a callback (example 2) and using the `string.is` function within it works.

This seems wrong, and I don't even know how I could create this bug?

Btw, it doesn't matter what kind of schema I create, I just used string as an example. Any `is` function seems affected.

What's weird to me: passing `z.string().is` returns false, while passing `(value) => z.string().is(value)` returns true. They should be the same thing?

I used `    "zod": "^2.0.0-beta.25"`

**Comment by merisbahti** [comment] 2020-12-04 21:13
> See this code:
> 
> ```ts
> const verifyer = <T,>(pred: (value: unknown) => value is T, value: unknown) => { return pred(value) }
> console.log(verifyer(string().is, 'hello')) // false
> console.log(verifyer((u: any): u is String => string().is(u), 'hello')) // true 
> console.log(string().is('hello')) // true
> ```
> 
> Passing the `is` function seems to return a bad value, however, creating a callback (example 2) and using the `string.is` function within it works.
> 
> This seems wrong, and I don't even know how I could create this bug?
> 
> Btw, it doesn't matter what kind of schema I create, I just used string as an example. Any `is` function seems affected.
> 
> I used ` "zod": "^2.0.0-beta.25"`

**Comment by merisbahti** [comment] 2020-12-04 21:13
oops accidentally closed, not intentional

**Comment by colinhacks** [comment] 2020-12-07 03:56
Not entirely sure what's happening here honestly. Here's the implementation of `.is`:

```ts
is(u: Input): u is Input {
  try {
    this.parse(u as any);
    return true;
  } catch (err) {
    return false;
  }
}
```

If you check to see what error is being thrown, it's this:

```
TypeError: Cannot read property 'parse' of undefined
    at ZodType.is (/Users/colinmcd94/Documents/Projects/zod/src/types/base.ts:165:12)
    at callback (/Users/colinmcd94/Documents/Projects/zod/src/playground.ts:4:10)
    at Object.<anonymous> (/Users/colinmcd94/Documents/Projects/zod/src/playground.ts:8:13)
```

Very strange, no idea why this wouldn't be defined. I'll look into it deeper when I have time, for now just go with the more verbose version.

**Comment by lantw44** [comment] 2020-12-08 01:52
> ```ts
> console.log(callback(z.string().is)); // false!?
> ```

Isn't it an expected behaviour? You don't specify `this` when calling the function, so it defaults to `undefined`.

**Comment by colinhacks** [comment] 2020-12-08 02:33
Figured out how to solve this by binding `this` in the constructor. Fixed in beta 28!

**Closed by colinhacks** 2020-12-08 02:33 UTC

**Comment by lantw44** [comment] 2020-12-09 02:15
Shouldn't users call `bind` themselves if they want to use a method as a regular function? If you just want to prevent these methods from being used in an invalid way, you can add `this: this` to the parameter list to require the caller to provide a valid `this` value.

**Comment by merisbahti** [comment] 2020-12-09 05:18
I've switched to `io-ts`... but...

> Shouldn't users call `bind` themselves if they want to use a method as a regular function?

and...

> > ```ts
> > console.log(callback(z.string().is)); // false!?
> > ```
> 
> Isn't it an expected behaviour? You don't specify `this` when calling the function, so it defaults to `undefined`.


What value is being provided by letting the user bind `this`?

I must query because I don't know, I've been coding without exposing/using `this` forever in js, and used `bind` once just for highcharts before they fixed their API.

If I was to author, I would either:

 * Use classes (if forced to), but then use arrow functions for my methods - this auto-binds `this` to the function.
 * Honestly... just use closures... There's too many footguns and misconceptions about JS classes. Closures are clean and performant. 

So instead of typing:
```javascript
class MyClass {
  constructor() {
    this.a = 5
  }
  someMethod() {
    return a + 5
  }
  otherMethod(newA) {
    this.a + 5
  }
}
```

I'd just do:

```javascript
const myClass = () => {
  let a = 0;
  return {
    someMethod: () => a
    otherMethod: (newA) => {a = newA}
  }
}
```
Which is more robust, works as expected, and performant.

But I guess this is just an opinion ;)

**Comment by lantw44** [comment] 2020-12-14 04:06
> I've switched to `io-ts`... but...
> 
> > Shouldn't users call `bind` themselves if they want to use a method as a regular function?
> 
> and...
> 
> > > ```ts
> > > console.log(callback(z.string().is)); // false!?
> > > ```
> > 
> > 
> > Isn't it an expected behaviour? You don't specify `this` when calling the function, so it defaults to `undefined`.
> 
> What value is being provided by letting the user bind `this`?

It isn't about the value. It is the default behaviour of JavaScript. Users should know they have to use `bind` or an arrow function if they want to use methods in this way. Setting extra properties on the instance may increase the memory usage.

> I must query because I don't know, I've been coding without exposing/using `this` forever in js, and used `bind` once just for highcharts before they fixed their API.
> 
> If I was to author, I would either:
> 
>     * Use classes (if forced to), but then use arrow functions for my methods - this auto-binds `this` to the function.

This can cause problems for users who want to subclass your classes. Since arrow functions are defined on the instance instead of the prototype, a subclass method does not override the arrow function of the same name in the super class.

>     * Honestly... just use closures... There's too many footguns and misconceptions about JS classes. Closures are clean and performant.

**Comment by merisbahti** [comment] 2020-12-15 12:48
Ok, I guess I just haven't found any need/use for classes in my career... 👍

**Comment by colinhacks** [comment] 2020-12-15 23:29
Most other methods are implemented with arrow methods. I used "normal" methods for these in particular because they're all overloaded. I couldn't figure out how to overload an arrow function method. Given that limitation, binding these methods in the constructor is a no brainer. Not doing so is a huge footgun as demonstrated by the existence of this issue.
