### ISSUE TITLE
Zod Template Literal Types

### ISSUE THREAD

**Issue by premshree** [colinhacks/zod#566] opened 2021-07-30 15:43 UTC
TypeScript 4.1 introduced template literal types, so we could define types like: 

```ts
type DateString = `${number}-${number}-${number}`;
```

It would be very cool if Zod allowed us to infer literal types. I'm not sure extending the current `literal` for this purpose is the best approach, but perhaps a new `templateLiteral` method that might look like:

```ts
const dateString = z.templateLiteral(z.number(), z.literal('-'), z.number(), z.literal('-'), z.number());
```

The above isn't as clean as defining a template literal type in TypeScript, but Zod will need some way of understanding the literal sequence and I wonder if the above format would make sense for it.

Do you think supporting template literal type checks and inference using `z.infer` is something on the horizon? Thank you!

**Comment by colinhacks** [comment] 2021-08-01 00:23
It's a good idea, and I haven't thought deeply about the right API for it. It would be a meaty project for anyone looking to contribute to Zod. There's a workaround described in #419 you can check out.

(Closing, duplicate of #419)

**Closed** 2021-08-01 03:27 UTC
