### ISSUE TITLE
Problem when specifying which properties to make required

### ISSUE THREAD

**Issue by kaydenthomson** [colinhacks/zod#1625] opened 2022-12-02 23:16 UTC
Following the example in the [readme.required](https://github.com/colinhacks/zod#required):

```
const user = z.object({
  email: z.string(),
  username: z.string(),
}).partial();

const requiredEmail = user.required({
  email: true,
})
```

<img width="314" alt="Screenshot 2022-12-02 at 4 14 05 PM" src="https://user-images.githubusercontent.com/9437192/205404896-7dde9a8d-7198-42b2-bc16-2997a670c4eb.png">

I get the following error

> Expected 0 arguments, but got 1.

**Comment by Ofadiman** [comment] 2022-12-04 08:41
Looks like duplicate of #1550. I updated `zod` to beta version (i.e. [3.20.0-beta.0](https://www.npmjs.com/package/zod/v/3.20.0-beta.0)) for now and wait for new version release.

**Closed** 2022-12-05 05:54 UTC
