### ISSUE TITLE
[Suggestion] Parse option that expects Output type as argument, to be used for casting default values

### ISSUE THREAD

**Issue by eliezra236** [colinhacks/zod#3143] opened 2024-01-16 14:10 UTC
Hi,
I am trying to use Zod for both validation and casting tool, so that I can define my buissness logic default values there and then I can pass a partly object to it and it fill up the gaps, a.k.a default values.

for example:

```ts
const userSchema = z.object({
	id: z.string(),
	coins: z.number().int().nonnegative().default(0),
});

const parsedUser = userSchema.parse({
	id: '123'
});
```
now that would work as intended, but the problem is that if I will add another mandatory field, for example `firstName`, all the places where I used user.parse() for filling in default values would break, and I wouldn't know about it on build time.
A workaround that I can do is either wrapping it under my own function, or do:
```ts
const parsedUser = user.parse({
	id: '123'
} satisfies z.infer<typeof userSchema >);
```

But having this as a built in option would be really helpful.

**Comment by JacobWeisenburger** [comment] 2024-01-16 14:30
duplicate of:
https://github.com/colinhacks/zod/issues/1748

**Closed** 2024-01-16 15:03 UTC
Labels: duplicate
