### ISSUE TITLE
DateType should be able to parse from other types

### ISSUE THREAD

**Issue by oof2win2** [colinhacks/zod#834] opened 2021-12-20 23:44 UTC
Zod's DateType is fairly limited, it expects an existing Date object. This is most often not how they are sent over the internet, and therefore I believe that it should be able to parse inputs such as ISO timestamps, etc., which can usually be fed into the Date constructor.
Regarding UNIX epoch timestamps, I also believe that the user should have the choice of setting whether it is milliseconds or seconds, as the JS standard differs from the standards of other apps, which can have seconds as units.

I'd be fine implementing this myself, just would like to hear opinions on this.

**Comment by scotttrinh** [comment] 2021-12-21 14:53
This (and other similar stringy issues) have come up before, so I'll try to add some context and help provide some ideas of how we handle this:

Fundamentally, Zod looks to compliment the TypeScript type system and give you runtime checking capabilities. As such, the `date` schema (like all of the other schemas) is analogous to TypeScript's `Date` type which represents the JavaScript `Date` object. None of the schemas have any hidden or implicit conversions/coercions going on, and I would personally be -1 on making `date` the first to have that behavior.

We've, so far, avoided making Zod (the core library) opinionated about the system in which in runs (browser, node, deno, others?) and the problem domain it is solving for (form validation, CSV conversion, database model parsing, HTTP requests, etc.) and as such, it's common to feel like Zod isn't giving you the tools you need to approach the IO boundary that you're trying to work through. For now, as the ecosystem is still growing to cover each of those cases, you'll find that you will end up writing a few helper schemas to cover your specific use cases. I think that's likely to become less and less the case as the ecosystem grows and people start to build the abstraction layer atop Zod that represents all of these disparate platforms and problem domains.

---

Thanks for bearing with me on that. On to the ideas!

Given that, you can look to how TypeScript handles this situation: with unions. If a value could truly be either a `string` or a `Date`, you can represent that as a `z.union([z.string(), z.date()])`, which corresponds to the type `string | Date` in TypeScript.

Now, I think what you're getting at is that we often deal with number or string values that represent dates, but we want to be able to pass them through our schemas and reliably get a `Date`. In that case you have a few options:

1. `refine(isISODate).transform(Date)` - Use a refinement function and then explicitly convert to a `Date`. (See https://github.com/colinhacks/zod/issues/482#issuecomment-906848102 for detailed example of this)
2. `preprocess(customCoercionCode)` - If you know which keys ought to be dates, you can use `preprocess` to convert them before the schema parses it so that you can use `z.date` directly.

My historical preference has been to prefer `refine -> transform`, but that is mostly due to `preprocess` coming out after my team's patterns have mostly been established.

---

Going to close as a duplicate of a number of other similar issues, but feel free to ping me in this thread or reopen if you have additional questions, ideas, or thoughts on this.

**Closed by scotttrinh** 2021-12-21 14:53 UTC

**Comment by oof2win2** [comment] 2021-12-21 15:53
Thanks for the explanation!
