### ISSUE TITLE
Inverse of `z.infer`?

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [colinhacks/zod#2131] opened 2023-03-02 22:44 UTC
I am not looking to generate dynamic code from static code like in #53. `z.infer` goes from `z.ZodType` to "unwrapped" TypeScript types. How do you implement the inverse? I tried the following but does not seem to work:

```
X extends z.infer<infer Y> ? Y : never
```

**Comment by JacobWeisenburger** [comment] 2023-03-03 15:42
It seems that you are asking for the ability to take a normal type and infer a zod schema from it. Is this correct?

this might be related to https://github.com/colinhacks/zod/discussions/1928

**Comment by make-github-pseudonymous-again** [comment] 2023-03-03 21:48
Yep, going from an output type to a Zod schema type. That discussion is very relevant. So I guess it's just `z.ZodType<Output>` modulo details.

**Comment by JacobWeisenburger** [comment] 2023-03-03 21:49
is it ok if I mark this as a duplicate of that?

**Comment by make-github-pseudonymous-again** [comment] 2023-03-03 22:19
No problem! Go ahead.

**Closed** 2023-03-03 22:27 UTC
Labels: duplicate
