### ISSUE TITLE
Field becomes optional when value is any or unknown

### ISSUE THREAD

**Issue by jasonkuhrt** [colinhacks/zod#1628] opened 2022-12-03 19:32 UTC
```ts
const s = z.object({ x: z.unknown() })
type s = z.infer<typeof s>
// s has { x?: unknown } but should be { x: unknown }
```

**Comment by colinhacks** [comment] 2022-12-04 21:35
I'd say this is actually behaving as intended. Currently Zod can't really differentiate between `{arg: string | undefined}` and `{arg?: string | undefined}`. When you pass a key schema `S` s.t. `undefined extends infer<typeof S>`, Zod will add the question mark. In this case `undefined` extends `unknown` (because everything does), hence the question mark. This also agrees with runtime behavior:

```ts
const schema = z.object({ x: z.unknown() });
schema.parse({}); // works
```

**Comment by jasonkuhrt** [comment] 2022-12-04 22:30
How does one write `anything but something must be passed in and it cannot be undefined`?

**Comment by colinhacks** [comment] 2022-12-05 20:40
> How does one write `anything but something must be passed in and it cannot be undefined`?

This is the best I've got:

```ts
const schema = z.object({
    field: z.custom((x) => x !== undefined),
  });
```

**Comment by colinhacks** [comment] 2022-12-05 20:42
> It would be really nice if we could define "any object" as a property (and it is a required property when it does schema validation).

Cool idea! Open to this as a PR. Just setting the "default shape" to `{}` should work, though you'll end up with an empty object every time unless you use `.passthrough()`.

```ts
z.object().passthrough()
```

**Comment by ranmocy** [comment] 2022-12-11 14:29
If you guys like me need to make sure the return type is compatible with existing interfaces, then you could do something like this:

```typescript
object({
  field: custom<MyType>((val) => val !== undefined && val !== null),
})
// Or
object({
  field: object({}).passthrough().refine<MyType>((val): val is MyType => val !== undefined && val !== null),
})
```

**Comment by lostpebble** [comment] 2022-12-12 17:27
> Cool idea! Open to this as a PR. Just setting the "default shape" to `{}` should work, though you'll end up with an empty object every time unless you use `.passthrough()`.

I've just added a PR which pretty much does exactly that (makes the shape an empty object and set the object to `"passthrough"`. Its added as the type `z.anyObject()`.

**Comment by igalklebanov** [comment] 2022-12-12 18:22
> I've just added a PR which pretty much does exactly that (makes the shape an empty object and set the object to "passthrough". Its added as the type z.anyObject().

Isn't that the purpose of [`z.record`](https://github.com/colinhacks/zod#records)?

Possible today:

```ts
z.record(z.unknown()) // don't care about key type.
```

Proposal:

```ts
z.record() // don't care about anything.
```

**Comment by santosmarco-caribou** [comment] 2022-12-13 01:15
> > Cool idea! Open to this as a PR. Just setting the "default shape" to `{}` should work, though you'll end up with an empty object every time unless you use `.passthrough()`.
> 
> 
> 
> I've just added a PR which pretty much does exactly that (makes the shape an empty object and set the object to `"passthrough"`. Its added as the type `z.anyObject()`.

What does it infer to? I'm almost certain it will infer to `{}`, which is the same as `unknown` and this will not correctly resemble empty objects. Actually, everything that extends an object will pass this from the inference point of view.

Of course, in reality, Zod is smart enough to let only objects pass. But if you then use this Schema as a function parameter validator, for example, Zod will parse the argument correctly, but TypeScript will not complain if you pass it a `2`.

There are some things we can do to solve this:

1. Add a check on the type that generates the ZodObject output to check if the output is `{}`, in which case it should transform it to `Record<string, never>`—but I don't like this very much because we already have Record schemas.

2. You could intersection the empty ZodObject with ZodBrand so that it has a brand that will not interfere on the parsing, but now TS knows that I can't pass a `2` to a function argument.

**Comment by lostpebble** [comment] 2022-12-13 06:35
> What does it infer to? I'm almost certain it will infer to `{}`, which is the same as `unknown` and this will not correctly resemble empty objects. Actually, everything that extends an object will pass this from the inference point of view.

It infers to `object` - which is a standard TypeScript type for object and makes sense in this situation.

These type assertions seem to be correct to me:
![image](https://user-images.githubusercontent.com/1508863/207243819-61a2ea87-7ae7-41e3-ba11-9d54f5d6dc3a.png)

**Comment by JacobWeisenburger** [comment] 2022-12-26 14:14
Has this been resolved? Is so, I'd like to close this issue.

**Closed** 2022-12-31 17:10 UTC
Labels: closeable?

**Comment by flex-hyuntae** [comment] 2024-10-02 13:23
`{ a: unknown }` and  `{ a?: unknwon}` are different

**Comment by tacomanator** [comment] 2024-12-01 00:31
I am facing problem explained by @flex-hyuntae . Tried various incantations of workarounds, such as

```ts
z.custom<Required<any> | unknown>((x) => x !== undefined)
```

This works for any only, but adding unknown always seems to end up in an optional property. In my case the types are from a 3rd party library and I can't seem to work with them without basically just setting the parent object to z.any() and giving up validating.

**Comment by tacomanator** [comment] 2025-04-30 00:33
Now possible in Zod 4 beta with the new [z.interface()](https://v4.zod.dev/v4#zinterface):

```ts
const s = z.interface({ x: z.unknown() })
type s = z.infer<typeof s>
// { x: unknown }
```

**Comment by mr-kelly** [comment] 2025-05-01 10:01
I am using this.
```typescript
args: z.object({}).catchall(z.any()),
```

However, it doesn't appear to be elegant enough.

**Comment by tacomanator** [comment] 2025-05-06 23:46
UPDATE: [latest beta removes `z.interface()`, it's now possible directly with `z.object()`:](https://github.com/colinhacks/zod/pull/4271#issuecomment-2850747211)

```
const s = z.object({ x: z.unknown() })
type s = z.infer<typeof s>
// { x: unknown }
```

**Comment by Spiritsurge** [comment] 2026-04-26 15:56
Just hit this on Zod 4.3.6 today, so confirming it carried over from Zod 3 unchanged. Same behavior on `z.any()`, `z.custom<unknown>()`, and `z.union([z.unknown()])` per a separate sweep.

Minimal repro:

```ts
import { z } from "zod";

const S = z.object({
  payload: z.unknown(),
  required: z.string(),
});

type Inferred = z.infer<typeof S>;
// Inferred is `{ required: string; payload?: unknown }`,
// `payload` is auto-optional even though no `.optional()` was applied.

// Assignment without `payload` succeeds, proves optional:
const a: Inferred = { required: "x" };

// And a strict shape that requires `payload` rejects `a`:
type Strict = { required: string; payload: unknown };
const b: Strict = a;
//                ^ Property 'payload' is missing in type '{ required: string; }'.
```

Where it bit us: a JSON-RPC-ish endpoint echoes the caller's signed payload back as an opaque blob, varies by action kind, always present on the wire. The natural schema is `z.object({ ..., payload: z.unknown() })` and the response type ends up with `payload?: unknown`, which then leaks a misleading `?:` into the public typed-client surface. Runtime parses are fine; it's purely a type-level annoyance.

We type-assert at the boundary so the public API stays honest:

```ts
sign: (claim, body) =>
  execute(raw.sign(claim, body), SignedActionResponseSchema, fetchImpl)
    as Promise<SignedActionResponse>,
```

Where `SignedActionResponse` is hand-authored with `payload: unknown` (required). Workable, but a `?`-mark and a cast we'd rather not have to explain to every new contributor.

Not blocking us, just adding a "still here in v4" data point in case it's useful for prioritization. Same behavior described in #2966 and #3730.

**Comment by tacomanator** [comment] 2026-04-28 04:30
@Spiritsurge did you AI this? It's wrong.

<img width="316" height="205" alt="Image" src="https://github.com/user-attachments/assets/3e918a0d-7f73-4750-b411-48244a6ff64e" />

**Comment by colinhacks** [comment] 2026-04-30 17:35
This behavior has been changed in Zod 4.
