### ISSUE TITLE
[Question] Custom error message for invalid type

### ISSUE THREAD

**Issue by jessykalycia** [colinhacks/zod#386] opened 2021-04-07 05:13 UTC
Suppose this code:

`export const userSchema = z.object({
  id: z.string().nonempty("Missing Parameter"),
  password: z.string().nonempty("Missing Parameter")
});`

If I want to have a custom invalid type error message, such as "Field id does not have the correct type", what can be done?
Neither the string or number functions have overloads for messages, meaning they don't accept a custom error message. Is there anything I can do to add this invalid type error message?

i.e.
`
z.string("Invalid type for id").nonempty("Missing Parameter")
`

**Comment by akomm** [comment] 2021-04-22 15:05
Just started using the library and had same issue. So I'm not sure if there not any better solution to this.

I checked where the default messages come from. The [defaultErrorMap](https://github.com/colinhacks/zod/blob/1c51624d32756804a0b02a2e18eab31f9234ec1f/src/defaultErrorMap.ts#L13)

And found one location where you can override it: [ParseParams in .parse & .parseSafe](https://github.com/colinhacks/zod/blob/1c51624d32756804a0b02a2e18eab31f9234ec1f/src/parser.ts#L18)

```ts
import * as z from 'zod';
import {defaultErrorMap} from 'zod/lib/src/defaultErrorMap';

// schema.parse works the same
schema.safeParse(data, {
  errorMap: (error, _ctx) => {
    if (error.code === z.ZodErrorCode.invalid_type) {
      if (error.expected === 'string') {
        return {message: 'custom message'};
      }
    }
    return defaultErrorMap(error, _ctx);
  }
});
```
This will fallback to the default, except your overrides...

It does not look very nice in my opinion. Not sure if that is the intended way to do it...

**Comment by kompot** [comment] 2021-04-23 14:24
Related issue
https://github.com/colinhacks/zod/issues/281

**Comment by colinhacks** [comment] 2021-04-25 02:35
Duplicate of #97, this is on the roadmap.

@akomm If you upgrade to Zod 3 you can just call `z.setErrorMap` anywhere and it will globally update the error map for all calls to `.parse/.safeParse` - no need to pass in the custom error map every time.

**Closed by colinhacks** 2021-04-25 02:35 UTC
