### ISSUE TITLE
Allow Custom Errors on any value?

### ISSUE THREAD

**Issue by bradennapier** [colinhacks/zod#97] opened 2020-07-25 10:18 UTC
Any reason not to allow defining the last argument for any value as an error message to allow overriding the error message for that property easily?  The current method is not really ideal, especially when you have many string props but need different errors.

A couple nice ways to handle it:

### Allow Last Param to be Error Message

> Would also accept a custom error that it would throw instead of ZodError (similar to Joi)

```typescript
const TestSchema = z.object({
	three: z.literal('hi').optional(),
	one: z.number(),
	two: z.literal(3, 'that isnt 3 dummy'),
	four: z.string('string not whatever you gave!'),
	five: z.date()
})
```

### Add a `.error()` option like Joi

```typescript
const TestSchema = z.object({
	three: z.literal('hi').optional(),
	one: z.number(),
	two: z.literal(3).error(new Error('that isnt 3 dummy')),
	four: z.string().optional().error(new Error('string not whatever you gave!')),
	five: z.date()
})
```

---

For the VSCode extension I am working on, these styles add the benefit that jsdoc can be used to transfer over error messaging easily:

![](https://media2.giphy.com/media/kHIevgJMwj1pGRCxEl/giphy.gif)

**Comment by vriad** [comment] 2020-07-27 07:45
This is on the roadmap. Though it'll likely be an object instead of a string to leave room for future API additions.

```ts
z.string({ message: "That's not a string!" });
```

**Comment by bradennapier** [comment] 2020-07-27 07:47
Agreed, good to know it's coming !

**Comment by hesyifei** [comment] 2020-07-31 02:21
It is also a very useful feature to customize the error message of e.g. `.union` and `.nullable`.

Currently `z.string().nullable().parse(undefined)` would throw

```
Issue #0: invalid_union at
Invalid input
```

which is very confusing for the user. It would be great if something like `z.string().nullable({ message: "This field can be a string or null, but not undefined." }).parse(undefined)` could produce:

```
Issue #0: invalid_union at
This field can be a string or null, but not undefined.
```

**Comment by amankkg** [comment] 2021-03-18 08:39
What about [yup#setLocale](https://github.com/jquense/yup#using-a-custom-locale-dictionary) API? It seems to be easier to handle global translations for both primitives and their methods

**Comment by vsimko** [comment] 2021-05-08 19:41
Hi, I noticed that if custom message is specified, the `errorMap` function will never be called.
https://github.com/colinhacks/zod/blob/630a2aa082fdcc5c1ebd76f8aa819bf07fd1f27f/deno/lib/helpers/parseUtil.ts#L88-L92

I have a use case where I want to use **localization keys as custom messages** and handle them inside the errorMap function which is currently not possible.

Would it be possible to update the implementation  to always go through the `errorMap` function ?

**Comment by colinhacks** [comment] 2021-05-15 22:23
I think hard-coding an error message should override the error map in this case. Based on my limited understanding of what you're trying to do, it sounds like an anti-pattern. Localization settings should be contextual, not baked into schemas. The recommended approach here is to create a separate error map for each language and either pass it as a parameter to `.parse()` or use `z.setErrorMap()` to set it globalls.

**Comment by vsimko** [comment] 2021-05-17 07:58
What if the schema is defined on a per-form basis (e.g react-hook-form) and I need to localize error messages (react-i18next).

```ts
// schema definition: notice the translation using t("...")
const ZMySchema = z.object({
  name: z.string().nonempty().regex(/^[A-Za-z ]$/, t("users:form.validNameRequired")),
});

// now registering the schema to the form
const form = useForm({ resolver: zodResolver(ZMySchema) });
```

**Comment by vsimko** [comment] 2021-05-17 08:19
Until I find a better solution, I implemented the following workaround in my code:
```ts
import i18n, { TFunction } from "i18next";

class TranslatedString extends String {
  toString(): string {
    return i18n.t(super.toString());
  }
}

/**
 * Use this for localization of zod messages.
 * The function has to be named `t` because it mimics the `t` function from `i18next`
 * thus our IDE provides code completion and static analysis of translation keys.
 */
export const t: TFunction = (key: string) => ({ message: new TranslatedString(key) });
```

The trick is to defer the evaluation of the `t()` function until the string is printed which could have also been achieved if zod accepted a function as a message.

**Comment by osdiab** [comment] 2021-05-18 11:35
I'm also looking forward to this - I'm using `zod` in forms, and if a user fails to enter a required field, i'd rather it say something like "X is required" instead of `Expected number, received nan`, but at the moment I don't see a good way to add that requiremnet.

**Comment by colinhacks** [comment] 2021-05-26 00:24
@osdiab you can globally modify every error Zod creates with Error Maps: https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#customizing-errors-with-zoderrormap

**Comment by osdiab** [comment] 2021-05-26 07:39
That's an alright workaround! One thing though is that it's a little too imprecise for me to necessarily make a correct error message - for I have this `number` input field and if it's empty then what gets passed to Zod is `NaN`, which may happen for other invalid inputs; but I can't distinguish that from just an empty input based on the context object that's provided, where it's already been parsed, so it's possible for me to end up saying `Required` when really the issue is `please enter a valid number`. Can be worked around by clever copy or just some custom code but the hope is to minimize the custom code necessary for any situation, so it leaves a little precision to be desired.

**Comment by adam-thomas-privitar** [comment] 2021-05-26 10:49
I think the issue with ZodErrorMap is theres often cases where you want a certain schema to return a different error for that specific schema. The limit of having only a message object in the granular case precludes you from having error objects returned by zod, for later parsing by an application to react to those errors. E.g. being able to return an object of an arbitary shape.

Ultimately, only being able to return a message string in the non-global case precludes you from having custom errors for a schema where you want to do i18n later or if you need to react to those errors based on some key in your application for whatever reason.

I'd suggest what would solve this is something like:

```
const ZMySchema = z.object({
  name: z.string().nonempty().regex(/^[A-Za-z ]$/, ({path}) => ({code: MY_CUSTOM_CODE, path)),
});

```

**Comment by osdiab** [comment] 2021-05-26 11:58
In my case given that the error happens at the `number()` stage I just want to be able to do this:

```
z.number({ message: "Make it a number, doofus!" });
```

or alternatively for more complicated circumstances,

```
z.number({ message: ({ issue, ctx }) => makeErrorMessage({ issue, ctx }) })
```

**Comment by YimingIsCOLD** [comment] 2021-07-23 15:30
I have created a PR #543 that your could set `required` or `invalid` messages to string, number and boolean. Would like to hear from you guys on ways to improve it.

**Comment by medihack** [comment] 2021-08-23 12:40
Zod is really super cool, but I also stumbled upon this issue here while figuring out how to use [React Hook Form resolvers](https://github.com/react-hook-form/resolvers) together with localized error messages using i18next. The API with a `message` property (like `z.string().min(5, { message: "Must be 5 or more characters long" })` is quite ok, but it must be possible to pass in an object as a message. Otherwise, it won't be possible to translate complex messages with [interpolations](https://www.i18next.com/translation-function/interpolation) in them. Is this still planned?

**Comment by dartess** [comment] 2021-09-01 12:04
Zod brought me out of two days of depression after going through several other libraries.

At the moment this is the only problem I have encountered. Against the background of everything else, this is a mere trifle, but nevertheless I am also waiting for a solution to this problem.

**Comment by vsimko** [comment] 2021-09-01 16:23
Let me share my latest workaround for this (updated since May 17):

```ts
// file: zod-translation.ts
import i18n, { TOptions } from "i18next";

class TranslatedString extends String {
  private readonly restArgs: (TOptions | string)[];

  constructor(private readonly key: string, ...restArgs: (TOptions | string)[]) {
    // if we used something else than an empty string here,
    // we would see the string being transformed to an array of chars
    // (seen in IntelliJ debugger)
    super("");

    this.restArgs = restArgs;
  }

  toString(): string {
    return i18n.t(this.key, ...this.restArgs);
  }
}

/**
 * Use this for localization of zod messages.
 * The function has to be named `t` because it mimics the `t` function from `i18next`
 * thus our IDE provides code completion and static analysis of translation keys.
 */
export function t(
  key: string,
  options: { path: string | string[] } | Record<string, unknown> = {}
): { message: string; path?: string[] } {
  const message: string = (new TranslatedString(key, options) as unknown) as string;
  const { path } = options;

  if (path === undefined) return { message };

  return {
    message,
    path: typeof path === "string" ? [path] : (path as string[]),
  };
}
```

Example usage:
```ts
import { t } from "./zod-translation.ts";

export const ZValidEncryptionKey = z
  .string()
  .regex(/^[a-zA-Z0-9]*$/, t("error.ZValidEncryptionKey.noSpacesAllowed"))
  .nullable();

**Comment by SrBrahma** [comment] 2022-02-08 04:13
It would be cool if there were community translation files for common errors, where we would import 'zod/locale/pt'; and globally or on parse we would enter the language code. [dayjs works like it](https://day.js.org/docs/en/i18n/loading-into-nodejs).

They would be dicts from errorId to the translated message.

Similar for custom errors, loading them would register the errorIds to their messages. They could have the `$x` pattern for the values in the strings like `$1 must be greater than $2!`, and on the schemas, they would be selected and populated via ~ ('myError.invalidABC', [var1, var2])

**Comment by LoicMahieu** [comment] 2022-04-07 13:27
Similar to `yup` which have a community driven package: [yup-locales](https://github.com/LoicMahieu/yup-locales)

**Comment by SrBrahma** [comment] 2022-04-07 18:42
> Similar to `yup` which have a community driven package: [yup-locales](https://github.com/LoicMahieu/yup-locales)

This is really good. @colinhacks can you take a look?

**Comment by btebbens** [comment] 2022-05-06 19:07
Landed here while working on an issue today where my react app with i18next translated literals were not getting used. I tried @vsimko's solution, but found it didn't work with i18next-parser (which I'm using to extract translations). The root issue is that the schema is created before i18next gets initialized (I'm doing so in a hook in the root component). I found an easy alternative which is to just move the schema code and its type _inside_ of the component:
```tsx
//react functional component
export const LoginForm = () => {

    //zod schema with literal strings to be translated with i18next
    const schema = z.object({
    username: z.string()
      .nonempty(t`Email is required`)
      .email(),
    password: z.string()
      .nonempty(t`Password is required`)
      .min(8, t`Password must be at least 8 characters`)
  });
  
  type Schema = z.infer<typeof schema>;

  //react-hook-form useForm hook w/ zodResolver
  const {register, handleSubmit, formState: {errors}} = useForm<Schema>({
    resolver: zodResolver(schema)
  });
...rest of component
}
```
Previously, my schema object and type were _above_ the LoginForm component itself and I only got the default messages. Now I have full type safety _and_ localized validation messages, which is awesome. Hope this helps someone else.

**Comment by SrBrahma** [comment] 2022-07-05 23:36
Up

**Comment by SrBrahma** [comment] 2022-09-04 08:55
Up

**Comment by bryantobing12** [comment] 2022-09-09 06:55
Is there a solution?

**Comment by medihack** [comment] 2022-09-19 13:42
Here is my (relatively simple) solution. Similar to @btebbens I build the schemas when I need them. But as I also use them in resolvers on the server (in my case [Blitz.js](https://blitzjs.com/docs/resolver-server-utilities#resolver-zod), but [tRPC](https://blitzjs.com/docs/resolver-server-utilities#resolver-zod) works similarly) I put them in an own file where they can be built with and without the `t` function. 

Simple example:
```
// app/core/validations.ts
const buildCreateProductSchema = (t?: TFunction) => z.object({
  name: z.string().regex(/^[a-zA-Z]*$/, t && { message: t("formErrors.invalid") })
})
```

**Comment by CharlesOnAir** [comment] 2022-10-19 16:53
up

**Comment by bombillazo** [comment] 2022-10-20 05:05
Hmmm just stumbled upon a usecase where we need a custom error for invalid_literal values when checking literals. :/

**Comment by deivuss331** [comment] 2022-10-26 17:45
I've trying to create schema with i18n error messages. Ended up on this solution:

```tsx
const schemaFactory = (t: TFunction): z.ZodType<ApiLoginRequest> =>
  z.object({
    email: z.string().email({ message: t('Please enter valid email') }),
    password: z
      .string()
      .min(MIN_PASSWORD_LENGTH, t('Minimum {{chars}} characters', { chars: MIN_PASSWORD_LENGTH }))
      .max(MAX_PASSWORD_LENGTH, t('Maximum {{chars}} characters', { chars: MAX_PASSWORD_LENGTH })),
  });

export default function LoginFormContainer() {
  const { t } = useTranslation();
  // memoize the schema to prevent recreating on each render
  const schema = useMemo(() => schemaFactory(t), [t]);
  const { register, handleSubmit, reset } = useForm({ defaultValues, resolver: zodResolver(schema) });

  // ...rest of your component
```

Hope it might help someone

**Comment by titenis** [comment] 2022-11-23 12:25
> I've been trying to create schema with i18n error messages. Ended up on this solution:
> 
> ```tsx
> const schemaFactory = (t: TFunction): z.ZodType<ApiLoginRequest> =>
>   z.object({
>     email: z.string().email({ message: t('Please enter valid email') }),
>     password: z
>       .string()
>       .min(MIN_PASSWORD_LENGTH, t('Minimum {{chars}} characters', { chars: MIN_PASSWORD_LENGTH }))
>       .max(MAX_PASSWORD_LENGTH, t('Maximum {{chars}} characters', { chars: MAX_PASSWORD_LENGTH })),
>   });
> 
> export default function LoginFormContainer() {
>   const { t } = useTranslation();
>   // memoize the schema to prevent recreating on each render
>   const schema = useMemo(() => schemaFactory(t), [t]);
>   const { register, handleSubmit, reset } = useForm({ defaultValues, resolver: zodResolver(schema) });
> 
>   // ...rest of your component
> ```
> 
> Hope it might help someone

Main problem with such schemaFactory initiated in components is that you cannot export and reuse this schema outside of this component. This defeats the main "goal is to eliminate duplicative type declarations"

**Comment by maxArturo** [comment] 2022-11-25 11:40
Hi all! This seems to be one of the oldest open issues in the repo, and the original header issue title seems to have been resolved some time ago with [custom errors and `errorMap`s](https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#customizing-errors-with-zoderrormap). 

However there are some additional asks that seem very useful and probably merit their own issues. Would it be better to open separate issues on these topics and discuss/track progress there instead? I took a quick look but couldn't find a great home for the following: 

- i8n support for error messages (@vsimko / @SrBrahma )
- catch-all per-call error customization for `schema.parse()` (@osdiab / @adam-thomas-privitar )

Let me know your thoughts! 🙏

**Comment by colinhacks** [comment] 2022-12-12 08:13
As @maxArturo said, this has been mostly implemented for a long time now - whoops. Almost every schema creation function `z.whatever` supports an options object with the `required_error` and `invalid_type_error` options.

```ts
const name = z.string({
  required_error: "Name is required",
  invalid_type_error: "Name must be a string",
});
```

This is true for all schema types.

```ts
z.object({ asdf: z.string() }, { required_error: "asdf" });
```

You can set an error map globally with `z.setErrorMap`.

```ts
const myErrorMap: z.ZodErrorMap = (val, ctx) => {
  return { message: "whatever" };
};
z.setErrorMap(myErrorMap);
```

You can set an error map on a per-schema basis

```ts
z.string({ errorMap: myErrorMap })
```

And you can set a contextual error map in a particular call to `.parse`.

```ts
z.string().parse("tuna", {errorMap: myErrorMap})
```

> i8n support for error messages

Tracked in other issues. 

Closing.

**Closed** 2022-12-12 08:13 UTC
