### ISSUE TITLE
Using `z.function(z.tuple([...]), ...).implement()` form results in TS2345 in TypeScript 4.8

### ISSUE THREAD

**Issue by 6XGate** [colinhacks/zod#1362] opened 2022-08-29 18:07 UTC
zod was listed in microsoft/TypeScript#50060 with several issues. I've actually encountered the issue listed for [src/tests/function.test.ts#L115](https://github.com/colinhacks/zod/blob/master/src/__tests__/function.test.ts#L115) in the zod tests.

**Comment by colinhacks** [comment] 2022-09-06 04:27
I'm not able to reproduce on the latest version of TypeScript (4.8.2)

**Comment by colinhacks** [comment] 2022-09-06 08:27
Fixed in `zod@3.19` 👍

**Closed by colinhacks** 2022-09-06 08:27 UTC

**Comment by JesusTheHun** [comment] 2022-09-14 16:40
@colinhacks I'm afraid it's not.
Tuple are defined with a rest parameter by default with both `typescript@4.7.4` and `typescript@4.8.3`.

```ts
const zTuple = z.tuple([z.number(), z.number()]);
type Tuple = z.infer<typeof zTuple>; 
// Expected    [number, number]
// Actual      [number, number, ...unknown[]]
```

https://stackblitz.com/edit/typescript-cgd2rk?file=index.ts

**Comment by 6XGate** [comment] 2022-09-14 16:52
Ouch, that's not correct. Tuples should only include those types passed.

**Comment by JesusTheHun** [comment] 2022-09-14 17:04
Eh, my bad. Strict mode was disabled 😅
