### ISSUE TITLE
Schema with either `strip()` or `passthrough()` throwing on unrecognized keys.

### ISSUE THREAD

**Issue by prescience-data** [colinhacks/zod#878] opened 2022-01-24 05:12 UTC
Interestingly I have just started getting a weird scenario where `z.object({}).strip()` and `z.object({}).passthrough()` are both throwing errors on any unexpected keys.

This is causing a massive error stack when I try to parse `process.env` with the message:

```
"Expected never, received string"
```

```typescript

// A handful of similar passthrough schemas...
const RedisEnvSchema = z
  .object({
    REDIS_HOST: z.string().default("queue.undetect.io"),
    REDIS_PORT: t.numberString().default(6379),
    REDIS_PASSWORD: z.string().optional()
  })
  .passthrough()

// Final strip schema...
export const EnvSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"])
})
.merge(RedisEnvSchema)
.strip()


// Parse function...
export const parse = <Output, Input = Output>(
  packageName: string,
  schema: ZodSchema<Output, ZodObjectDef, Input>,
  defaultValues: Partial<Output> = {}
): Output => {
  try {
    return schema.parse({ ...defaultValues, ...process.env })
  } catch (error) {
    throw new EnvSchemaParseError(packageName, error)
  }
}


```

**Comment by prescience-data** [comment] 2022-01-27 10:16
Additional context: 
The problem disappeared when switching to a chain of `.extend()` calls, but not sure why...

**Comment by JacobWeisenburger** [comment] 2022-02-21 20:19
I tested the code you provided, but I couldn't reproduce `"Expected never, received string"`. Can you send some example code that produces the error you are having? Perhaps you could use something like [codesandbox](https://codesandbox.io/).

**Comment by colinhacks** [comment] 2022-03-01 23:26
`.extend` and `.merge` are subtlely different. When you call `A.merge(B)`, the result inherits the unknown keys policy from B. With A.extend({...}) the result has the same behavior as A (obviously). I recommend using `extend` wherever possible since its behavior is less surprising. 

I also couldn't duplicate the bug though. Closing for now.

**Closed by colinhacks** 2022-03-01 23:26 UTC
Labels: bug-unconfirmed
